apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["bilbomd/mongo"]'
    management.cattle.io/ui-managed: "true"
  name: {{ .Values.mongo.name }}
  namespace: {{ .Values.namespace }}
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: {{ .Values.mongo.name }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 27017tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-{{ .Values.namespace }}-{{ .Values.mongo.name }}
  sessionAffinity: None
  type: ClusterIP
