# -*- coding: utf-8 -*-
"""Copy of Scoper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJBsqc_gZoN-IWkweM0K9HCuQLzRyI1V

#Scoper
Scoper is a novel pipeline that uses a combination of classical algorithms and deep-learning techniques to find structures, along with magnesium ion binding sites that fit a given saxs profile, given an initial structure to work with.

<br>
<img src=https://drive.google.com/uc?id=1Jn7bdC88ZxGLW9sDUezOAz8dLphRK4Q0 width="500">

A novel deep neural network was created for this pipeline which we named IonNet. IonNet is used to predict magnesium binding sites for RNA structures. The input for our model is a PDB file of the RNA structure. If you prefer to only use IonNet to predict the most likely magnesium binding sites, you can do so using the "configurations" cell below.

If all you have is the sequence, we suggest using RNAComposer or DeepFoldRNA
to create a predicted structure.

<br>
<img src=https://drive.google.com/uc?id=1HKfKcl1Y8-dzVoAgRUvh67nvMYlXh3kd width="2000">



The source code and the trained model can be found [here](https://github.com/dina-lab3D/IonNet)





<strong>For Citation use: </strong> [IonNet paper (I hope)]()
"""

#@title Upload your PDB file and SAXS (Optional) file to the drive
from google.colab import files
#@markdown **If your prediction type uses Saxs data, please upload the .dat file.**
uploaded = files.upload()

#@title Configurations
from google.colab import files
import re
import os
import sys
from IPython.display import clear_output
from google.colab import files

prediction_type = 'Saxs' #@param ["Top", "Saxs"]
output_dir = 'ScoperResults' #@param {type:"string"}
kgs_k = 1000 #@param {type:"integer"}
top_k = 1 #@param {type:"integer"}
multifoxs = True #@param {type:"boolean"}
if kgs_k > 1000:
  kgs_k = 1000
if top_k > kgs_k:
  top_k = kgs_k

pdb_file_path = "/content/"
dat_file_path = "/content/"
if uploaded.keys():
  for file_name in uploaded.keys():
    if file_name.endswith("pdb"):
      pdb_file_path += file_name
    elif file_name.endswith("dat"):
      dat_file_path += file_name
  print(f'found file {pdb_file_path}')
  print(f'found file {dat_file_path}')
else:
  print('No file was uploaded, please run the cell above.', file=sys.stderr)
  raise Exception('need to upload file')

# remove whitespaces
output_dir = "".join(output_dir.split())
output_dir = re.sub(r'\W+', '', output_dir)



visualize_results = True #@param {type:"boolean"}
save_to_google_drive = False #@param {type:"boolean"}

#@markdown ---
#@markdown  To run Scoper hit `Runtime` -> `Run all`

#@markdown  **kgs_k**: selects how many structures KGSrna will produce.
#@markdown This only matters for SAXS  prediction type.

#@markdown  **top_k**: selects how many of the best initial structures to run the rest of the pipeline on.

#@markdown  **multifoxs**: selects if to run stage 5 in the pipeline. Will only work if top_k > 2


if save_to_google_drive == True:
  from pydrive.drive import GoogleDrive
  from pydrive.auth import GoogleAuth
  from google.colab import auth
  from oauth2client.client import GoogleCredentials
  auth.authenticate_user()
  gauth = GoogleAuth()
  gauth.credentials = GoogleCredentials.get_application_default()
  drive = GoogleDrive(gauth)
  print("Saving results into Drive")

# Commented out IPython magic to ensure Python compatibility.
# #@title Clone IonNet trained model and accompanying scripts
# 
# 
# %%bash
# 
# # install dependencies
# pip -q install biopython
# pip install py3Dmol
# 
# # download model
# if [ ! -d "IonNet/" ]; then
#   git clone https://github.com/dina-lab3D/IonNet --quiet
#   else
#   cd IonNet/
#   git pull
#   cd ../
# fi
# 
# touch IonNet
# 
# # install reduce
# if [ ! -d "reduce/" ]; then
#   git clone https://github.com/rlabduke/reduce.git --quiet
# fi
# 
# 
# 
#

#@title Script Installations
# Move reduce and install
import shutil
shutil.move("/content/reduce", "/content/IonNet/scripts/scoper_scripts")

# Install reduce
! cd /content/IonNet/scripts/scoper_scripts/reduce && make
! cd /content/IonNet/scripts/scoper_scripts/reduce && sudo make install


# Install rnaview
!tar -xf /content/IonNet/scripts/scoper_scripts/RNAVIEW.tar -C /content/IonNet/scripts/scoper_scripts/

# Untar KGSrna
!tar -xf /content/IonNet/scripts/scoper_scripts/KGSrna.tar -C /content/IonNet/scripts/scoper_scripts/

#@title install IMP
# Install IMP for FoXs and multi_foxs_combination
!echo "deb https://integrativemodeling.org/latest/download $(lsb_release -cs)/" > /etc/apt/sources.list.d/salilab.list
!wget -O /etc/apt/trusted.gpg.d/salilab.asc https://salilab.org/~ben/pubkey256.asc
!apt update
!apt install imp
import sys
sys.path.append('/usr/lib/python3.6/dist-packages')

#@title Viewer Installations
!apt-get update
!apt-get install gnuplot-x11 gnuplot
!apt-get -y install ghostscript

#@title Install Pytorch Geometric

# Add this in a Google Colab cell to install the correct version of Pytorch Geometric.
!pip uninstall torch -y
!pip install torch==1.13.1+cu116 -f https://download.pytorch.org/whl/torch_stable.html
import torch

def format_pytorch_version(version):
  return version.split('+')[0]

TORCH_version = torch.__version__
TORCH = format_pytorch_version(TORCH_version)

def format_cuda_version(version):
  return 'cu' + version.replace('.', '')

CUDA_version = torch.version.cuda
CUDA = format_cuda_version(CUDA_version)

!pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-sparse      -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-cluster     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-geometric==2.2.0
!pip install wandb
!pip install torchmetrics==0.7.2

# Commented out IPython magic to ensure Python compatibility.
#@title Run Scoper
#@markdown **You may choose the model's threshold for prediction (default is 0.3)**

#@
# %cd /content
model_sensitivity = 0.3 #@param {type:"slider", min:0, max:1, step:0.01}
file_path = 'IonNet/inference/inference_config.py'
with open(file_path, 'r') as file:
    content = file.read()

new_content = re.sub(r'positive_thresh=.+', f'positive_thresh={model_sensitivity},', content)
with open(file_path, 'w') as file:
    file.write(new_content)
# Read the contents of the config.py file
with open(file_path, 'r') as file:
    content = file.read()
# %rm -rf /content/newpdb_*
# %rm -rf /content/KGSRNA
import py3Dmol
os.chdir("/content/")
if "IonNet" not in dir():
  from timeit import default_timer as timer
  import sys
  sys.path.insert(0, '/content/IonNet/')
  from IonNet import *

ionNet_dir_path = "/content/IonNet"

if not os.path.exists(ionNet_dir_path):
    print("Can't find trained ionNet, aborting.", file=sys.stderr)
    error = True

# Check if pdb file exists
if not os.path.exists(pdb_file_path):
  print("Cannot find PDB file, please make sure to upload in the above cell and make sure the names match", file=sys.stderr)

if prediction_type == "Top":
#   %cd IonNet
  ! python mgclassifierv2.py -bd /content inference -o /content/ -fp $pdb_file_path -it top -mp models/trained_models/wandering-tree-178.pt -cp models/trained_models/wandering-tree-178_config.npy -do content/results.txt -fs a -mfs a


elif prediction_type == "Saxs":
#   %cd IonNet
  mfr = "-mfr True" if multifoxs else ""
  ! python mgclassifierv2.py -bd /content scoper -fp $pdb_file_path -ahs /content/IonNet/scripts/scoper_scripts/addHydrogensColab.pl -sp $dat_file_path -kk 1 -it sax -mp models/trained_models/wandering-tree-178.pt -cp models/trained_models/wandering-tree-178_config.npy -fs foxs -mfcs multi_foxs_combination -kk $kgs_k -tk $top_k -mfs multi_foxs $mfr

# def plot_structure(nb_name, pdb_path):
#     with open(pdb_path) as ifile:
#       predicted = "".join([x for x in ifile])
#     r,g,b = 0,0,255
#     print(f"\033[38;2;{r};{g};{b}m {nb_name} Predicted model \033[38;2;255;255;255m")
#     view = py3Dmol.view(width=500, height=500)
#     view.addModelsAsFrames(predicted)
#     view.setStyle({'model': 0}, {"cartoon": {'arrows':True, 'color': 'blue'}})
#     view.zoomTo()
#     view.show()



# file_ending = "nanonet_backbone_cb.pdb" if not reconsrtuct_side_chains_using_modeller else "nanonet_full_relaxed.pdb"
# if visualize_results and not write_into_single_pdb_file:
#   print("Showing nanonet predicted structures")
#   for seq, nb_name in seq_iterator(input_nb):
#     plot_structure(nb_name, os.path.join(output_dir, f"{nb_name}_{file_ending}"))

# Commented out IPython magic to ensure Python compatibility.
#@title Visualize Structure

# %cd /content/
!pwd

import py3Dmol
import os
import math

def get_top_files(filename):
  rna_path = os.path.join(os.getcwd(), filename, f'{filename}_rna_.pdb')
  predicted_mg_path = os.path.join(os.getcwd(), filename, f'new_probe_{filename}_probes.pdb')
  return rna_path, predicted_mg_path

def get_best_scoring_structure(filename):
  score = math.inf
  best_structure = ""
  num_of_mg = 0
  for folder in os.listdir(os.getcwd()):
    if os.path.isdir(folder) and (folder.startswith("newpdb") or folder.startswith(filename)):
      cur_score, cur_mg = get_lowest_scoring_ensemble(folder)
      if cur_score < score:
        score = cur_score
        best_structure = folder
        num_of_mg = cur_mg
  return best_structure, score, num_of_mg

def get_lowest_scoring_ensemble(folder_name):
  score = math.inf
  num_of_mg = 0
  ensemble_path = os.path.join(folder_name, 'ensemble_scores')
  for file in os.listdir(ensemble_path):
    full_path = os.path.join(os.getcwd(), ensemble_path)
    with open(os.path.join(full_path, file)) as f:
      cur_score = float(f.readlines()[1])
      cur_mg = file.split("_")[2].split('.')[0]
      if cur_score < score:
        score = cur_score
        num_of_mg = int(cur_mg)
  return score, num_of_mg
if prediction_type == "Saxs":
  print('Visualizing Scoper results with SAX mode')
  print("Showing Scoper's predicted Mg ions")
  rna=""
  pdb_file_base = pdb_file_path.split('.')[0].split('/')[2]
  best_structure, score, num_of_mg = get_best_scoring_structure(pdb_file_base)
  print(f"The best scoring stand-alone  structure is {best_structure} with a score of {score} and a total of {num_of_mg} Mg ions added")
  if multifoxs and top_k > 2:
    with open('/content/IonNet/MultiFoXS/result.txt', 'r') as f:
      line = f.readline()
      mf_score = line.split(' ')[0]
      print(f"ran multifoxs, the best scoring combination of structures has a score of: {mf_score}")
  rna_file_name = os.path.join(best_structure, best_structure+"_rna_.pdb")
  ion_file_name = os.path.join(best_structure, "new_probe_"+best_structure+"_probes.pdb")
  with open(rna_file_name) as ifile:
    lines = ifile.readlines()
    for line in lines:
      rna += line
  ions = ""
  with open(ion_file_name) as ifile:
      lines = ifile.readlines()
      for line in lines:
        if "PB" in line:
          line = line.replace("PB", "MG")
          line = line.replace("ATOM  ", "HETATM")
        ions += line
  r,g,b = 0,0,255
  view = py3Dmol.view(width=500, height=500)
  view.addAsOneMolecule(rna+ions, "pdb")
  view.setStyle({'model': 0}, {"cartoon": {'arrows':True, 'color': 'white'}})
  view.setStyle({'resn':'UNK'}, {"sphere": {'color': 'lightgreen'}})
  view.zoomTo()
  view.show()

if prediction_type == "Top":
  print('Visualizing Scoper results with Top mode')
  rna=""
  pdb_file_base = pdb_file_path.split('.')[0].split('/')[2]
  rna_path, predicted_mg_path = get_top_files(pdb_file_base)
  with open(rna_path) as ifile:
    lines = ifile.readlines()
    for line in lines:
      rna += line
  ions = ""
  with open(predicted_mg_path) as ifile:
      lines = ifile.readlines()
      for line in lines:
        if "PB" in line:
          line = line.replace("PB", "MG")
          line = line.replace("ATOM  ", "HETATM")
        ions += line
  original_mg_path = os.path.join(os.getcwd(), pdb_file_base, f'{pdb_file_base}_mg_.pdb')

  with open(original_mg_path) as mg_file:
    lines = mg_file.readlines()
    for line in lines:
      ions += line


  r,g,b = 0,0,255
  view = py3Dmol.view(width=500, height=500)
  view.addAsOneMolecule(rna+ions, "pdb")
  view.setStyle({'model': 0}, {"cartoon": {'arrows':True, 'color': 'white'}})
  view.setStyle({'resn':'UNK'}, {"sphere": {'color': 'orange'}})
  view.setStyle({'resn':'MG'}, {"sphere": {'color': 'lightgreen'}})
  view.zoomTo()
  view.show()

# Commented out IPython magic to ensure Python compatibility.
import subprocess
import os

# !apt-get update
# !apt-get install gnuplot-x11 gnuplot
#@title Visualize SAXS curves
if prediction_type == "Sax":
#   %cd /content/
  best_structure_dat_file = f"{best_structure}/sax_work_dir/{os.path.basename(dat_file_path)}/multi_state_model_{num_of_mg}_1_1.dat"
  # run regular foxs on the original pdb.
  ! foxs $pdb_file_path $dat_file_path
  regular_saxs_output_path = f"/content/{os.path.basename(pdb_file_path).split('.')[0] + '_' + os.path.basename(dat_file_path)}"

  # run plot
  ! IonNet/testing/plotFit1.pl $regular_saxs_output_path 1 original-fit $best_structure_dat_file 2 best-fit

  # convert eps to png
  eps_path = os.path.splitext(regular_saxs_output_path)[0] + ".eps"
  print(eps_path)
  # convert eps to png
  from PIL import Image
  eps_image = Image.open(eps_path)
  eps_image.load(scale=10)
  eps_image.save("curves.png")
  from IPython.display import Image
  Image('curves.png')
else:
  print("Using mode other than SAXS, this section did not run.")

"""#Results
if you ran MultiFoXS results can be found here:
/content/IonNet/MultiFoXS/result.txt

#Acknowledgements:

If you've used our program, the following scripts were used and we would like to give our thanks to the following:

**reduce** - /content/IonNet/scripts/scoper_scripts/reduce/LICENSE.txt

**rnaview** - /content/IonNet/scripts/scoper_scripts/RNAVIEW/README

**KGSrna** -  /content/IonNet/scripts/scoper_scripts/Software/Linux64/KGSrna/readme.txt

**IMP** - https://integrativemodeling.org/

If you've run our program, all README licensing can be found with /content/IonNet/scoper_scripts/
"""