"""Tests for strip_cofactors.py."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent))
import strip_cofactors as sc  # noqa: E402


ATOM_FAD = "HETATM    1  N1  FAD A 902      10.000  10.000  10.000  1.00  0.00           N\n"
ATOM_HEM = "HETATM    2  FE  HEM A 901      11.000  11.000  11.000  1.00  0.00          FE\n"
ATOM_PCA = "ATOM      3  N   PCA A   1      12.000  12.000  12.000  1.00  0.00           N\n"
ATOM_GLN = "ATOM      4  N   GLN A   2      13.000  13.000  13.000  1.00  0.00           N\n"
ATOM_NAG = "HETATM    5  C1  NAG A 903      14.000  14.000  14.000  1.00  0.00           C\n"
REMARK   = "REMARK   generated by test\n"


class TestStripCofactors:
    def test_strips_fad(self):
        kept, removed = sc.strip_cofactors([ATOM_FAD, ATOM_GLN])
        assert kept == [ATOM_GLN]
        assert removed == {"FAD": 1}

    def test_strips_hem(self):
        kept, removed = sc.strip_cofactors([ATOM_HEM, ATOM_GLN])
        assert kept == [ATOM_GLN]
        assert removed == {"HEM": 1}

    def test_strips_pca(self):
        kept, removed = sc.strip_cofactors([ATOM_PCA, ATOM_GLN])
        assert kept == [ATOM_GLN]
        assert removed == {"PCA": 1}

    def test_preserves_standard_residues(self):
        kept, removed = sc.strip_cofactors([ATOM_GLN])
        assert kept == [ATOM_GLN]
        assert removed == {}

    def test_preserves_carbohydrates(self):
        """NAG is handled by GLYCAM, not a cofactor to be stripped."""
        kept, removed = sc.strip_cofactors([ATOM_NAG, ATOM_GLN])
        assert kept == [ATOM_NAG, ATOM_GLN]
        assert removed == {}

    def test_preserves_non_atom_lines(self):
        kept, removed = sc.strip_cofactors([REMARK, ATOM_FAD, ATOM_GLN])
        assert REMARK in kept
        assert ATOM_GLN in kept
        assert ATOM_FAD not in kept

    def test_strips_multiple_cofactor_types(self):
        lines = [ATOM_FAD, ATOM_HEM, ATOM_PCA, ATOM_GLN, REMARK]
        kept, removed = sc.strip_cofactors(lines)
        assert len(kept) == 2  # GLN + REMARK
        assert removed == {"FAD": 1, "HEM": 1, "PCA": 1}

    def test_counts_multiple_atoms_per_cofactor(self):
        fad2 = ATOM_FAD.replace("    1  N1", "    2  C1")
        kept, removed = sc.strip_cofactors([ATOM_FAD, fad2, ATOM_GLN])
        assert removed == {"FAD": 2}
        assert kept == [ATOM_GLN]

    def test_empty_input(self):
        kept, removed = sc.strip_cofactors([])
        assert kept == []
        assert removed == {}

    def test_all_unsupported_cofactor_names_are_strings(self):
        for name in sc.UNSUPPORTED_COFACTORS:
            assert isinstance(name, str)
            assert 1 <= len(name) <= 3


class TestRunFile:
    def test_modifies_pdb_inplace(self, tmp_path):
        pdb = tmp_path / "test.pdb"
        pdb.write_text(ATOM_FAD + ATOM_GLN, encoding="utf-8")
        sc._run(pdb)
        content = pdb.read_text()
        assert "FAD" not in content
        assert "GLN" in content

    def test_writes_sidecar_json(self, tmp_path):
        pdb = tmp_path / "test.pdb"
        pdb.write_text(ATOM_FAD + ATOM_HEM + ATOM_GLN, encoding="utf-8")
        sc._run(pdb)
        sidecar = tmp_path / "stripped_cofactors.json"
        assert sidecar.exists()
        data = json.loads(sidecar.read_text())
        assert data["stripped"]["FAD"] == 1
        assert data["stripped"]["HEM"] == 1
        assert "note" in data

    def test_sidecar_written_even_when_nothing_stripped(self, tmp_path):
        pdb = tmp_path / "test.pdb"
        pdb.write_text(ATOM_GLN, encoding="utf-8")
        sc._run(pdb)
        sidecar = tmp_path / "stripped_cofactors.json"
        assert sidecar.exists()
        data = json.loads(sidecar.read_text())
        assert data["stripped"] == {}
